version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo-person
    ports:
      - "27017"
    networks:
      - person-network
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
    container_name: elasticsearch-person
    ports:
      - "9200"
      - "9300"
    environment:
      - "discovery.type=single-node"
      - "cluster.name=elasticsearch"
    networks:
      - person-network
      
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    container_name: kibana-person
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch-person:9200
    networks:
      - person-network
    depends_on:
      - elasticsearch
      
  person-proj:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: rmaia/person-project-mongo
    container_name: person-proj-mongo
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mongo-person
    networks:
      - person-network
    depends_on:
      - mongo
      
networks:
  person-network:
    driver: bridge